
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author intel
 */
public class Transaksi extends javax.swing.JFrame {

    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pesan = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CMakan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CMinum = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        MA = new javax.swing.JRadioButton();
        NA = new javax.swing.JRadioButton();
        NG = new javax.swing.JRadioButton();
        R = new javax.swing.JRadioButton();
        air = new javax.swing.JRadioButton();
        teh = new javax.swing.JRadioButton();
        teler = new javax.swing.JRadioButton();
        jeruk = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        total = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 24)); // NOI18N
        jLabel1.setText("EXPOST Restaurant");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 280, 50);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("Makanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 100, 20);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Minuman");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 130, 40);

        Pesan.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan);
        Pesan.setBounds(320, 70, 80, 30);

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel21.setText("Masukkan Pesanan Anda");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(20, 40, 180, 30);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 60, 30);

        CMakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(CMakan);
        CMakan.setBounds(80, 200, 90, 20);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 60, 30);

        CMinum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(CMinum);
        CMinum.setBounds(90, 320, 90, 20);

        clear.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(410, 70, 80, 30);

        print.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(500, 70, 90, 30);

        buttonGroup1.add(MA);
        MA.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        MA.setText("Mie Ayam");
        getContentPane().add(MA);
        MA.setBounds(160, 160, 90, 30);

        buttonGroup1.add(NA);
        NA.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        NA.setText(" Nasi Ayam");
        getContentPane().add(NA);
        NA.setBounds(20, 130, 100, 30);

        buttonGroup1.add(NG);
        NG.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        NG.setText("Nasi Goreng");
        getContentPane().add(NG);
        NG.setBounds(20, 160, 110, 30);

        buttonGroup1.add(R);
        R.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        R.setText("Rawon");
        getContentPane().add(R);
        R.setBounds(160, 130, 80, 30);

        buttonGroup2.add(air);
        air.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        air.setText("Air Mineral");
        getContentPane().add(air);
        air.setBounds(160, 280, 100, 30);

        buttonGroup2.add(teh);
        teh.setText("Es Teh");
        getContentPane().add(teh);
        teh.setBounds(20, 250, 80, 30);

        buttonGroup2.add(teler);
        teler.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        teler.setText("Es Teler");
        getContentPane().add(teler);
        teler.setBounds(20, 280, 120, 30);

        buttonGroup2.add(jeruk);
        jeruk.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jeruk.setText("Es Jeruk");
        getContentPane().add(jeruk);
        jeruk.setBounds(160, 250, 90, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Total Harga ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 360, 90, 30);

        total.setColumns(20);
        total.setRows(5);
        jScrollPane1.setViewportView(total);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 360, 210, 80);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 70, 80, 30);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(690, 70, 90, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Makanan", "Minuman", "Jumlah Makanan", "Jumlah Minuman"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 150, 470, 300);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Pesan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 70, 90, 30);
        getContentPane().add(tgl);
        tgl.setBounds(120, 70, 150, 30);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 840, 500);

        jLabel9.setText(" Nama Kasir :  Adelia Nova");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 40, 200, 30);

        setBounds(0, 0, 819, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        // TODO add your handling code here:
        int mkn;
        String makan;
        if(NA.isSelected())
        {
             makan= "ayam";
             if(CMakan.equals("2"))
             {
                 mkn = 15000*2;
             }else if(CMakan.equals("3"))
             {
                 mkn = 15000*3;
             }else if(CMakan.equals("4"))
             {
                 mkn = 15000*4;
             }
             else{
                 mkn = 15000;
             }
             
        }
        else if(NG.isSelected())
        {
            makan= "nasi";
             if(CMakan.equals("2"))
             {
                 mkn = 10000*2;
             }else if(CMakan.equals("3"))
             {
                 mkn = 10000*3;
             }else if(CMakan.equals("4"))
             {
                 mkn = 10000*4;
             }
             else{
                  mkn = 10000;
             }
        }
        else if(R.isSelected())
        {
            makan="rawon";
              if(CMakan.equals("2"))
             {
                 mkn = 20000*2;
             }else if(CMakan.equals("3"))
             {
                 mkn = 20000*3;
             }else if(CMakan.equals("4"))
             {
                 mkn = 20000*4;
             }
             else{
                  mkn = 20000;
             }
        }
        else{
            makan="mie";
             if(CMakan.equals("2"))
             {
                 mkn = 10000*2;
             }else if(CMakan.equals("3"))
             {
                 mkn = 10000*3;
             }else if(CMakan.equals("4"))
             {
                 mkn = 10000*4;
             }
             else
             {
                 mkn = 10000;
             }
        }
        int mnm;
        String minum;
         if(teh.isSelected())
        {
             minum= "teh";
             if(CMinum.equals("2"))
             {
                 mnm= 5000*2;
             }else if(CMinum.equals("3"))
             {
                  mnm= 5000*3;
             }else if(CMinum.equals("4"))
             {
                  mnm= 5000*4;
             }
             else
             {
                 mnm= 5000;
             }
        }
        else if(teler.isSelected())
        {
            minum= "teler";
             if(CMinum.equals("2"))
             {
                 mnm= 8000*2;
             }else if(CMinum.equals("3"))
             {
                  mnm= 8000*3;
             }else if(CMinum.equals("4"))
             {
                  mnm= 8000*4;
             }
             else{
                 mnm= 8000;
             }
        }
        else if(air.isSelected())
        {
            minum="air";
             if(CMinum.equals("2"))
             {
                 mnm= 4000*2;
             }else if(CMinum.equals("3"))
             {
                  mnm=4000*3;
             }else if(CMinum.equals("4"))
             {
                  mnm= 4000*4;
             }else
             {
                 
                 mnm= 4000;
             }
        }
        else{
            minum="jeruk";
              if(CMinum.equals("2"))
             {
                 mnm= 7000*2;
             }else if(CMinum.equals("3"))
             {
                  mnm= 7000*3;
             }else if(CMinum.equals("4"))
             {
                  mnm= 7000*4;
             }else
             {
                 mnm= 7000;
             }
        }
         int Total = mkn + mnm;
         total.setText("Total Harga " + Total);
         String SQL = "INSERT INTO tb_resto(`makan`, `minum`, `jml_mkn`, `jml_minum`)"+
            "VALUES('"+makan+"','"+minum+"',"+CMakan+","+CMinum+")";
               int status = KoneksiDB.execute(SQL);
               if (status == 1)
               {
                   JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                   selectData();
               }
               else{
                   JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
               }
    }//GEN-LAST:event_PesanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        total.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int baris = tabel.getSelectedRow();
        if (baris != -1)
        {
            String No = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_resto WHERE makan='"+No+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
           JOptionPane.showMessageDialog(this,"Pilih baris terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        
        int baris = tabel.getSelectedRow();
        if(baris != 1)
        {
            if("Nasi Ayam".equals(tabel.getValueAt(baris, 0).toString()))
            {
                NA.setSelected(true);
            }
            else if ("Nasi Goreng".equals(tabel.getValueAt(baris, 0).toString()))
            {
                NG.setSelected(true);
            }
            else if ("Mie Ayam".equals(tabel.getValueAt(baris, 0).toString()))
            {
                MA.setSelected(true);
            }
            else
            {
                R.setSelected(true);
            }
            
            if("Es Teh".equals(tabel.getValueAt(baris, 1).toString()))
            {
                teh.setSelected(true);
            }
            else if ("Es Jeruk".equals(tabel.getValueAt(baris, 1).toString()))
            {
               jeruk.setSelected(true);
            }
            else if ("Es Teler".equals(tabel.getValueAt(baris, 1).toString()))
            {
                teler.setSelected(true);
            }
            else
            {
               air.setSelected(true);
            }
            
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
         MessageFormat header = new MessageFormat ("Daftar Transaksi Patria Stationary");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        try{
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e)
                {
            System.err.format("Cannot Prnt %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMakan;
    private javax.swing.JComboBox<String> CMinum;
    private javax.swing.JRadioButton MA;
    private javax.swing.JRadioButton NA;
    private javax.swing.JRadioButton NG;
    private javax.swing.JButton Pesan;
    private javax.swing.JRadioButton R;
    private javax.swing.JRadioButton air;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jeruk;
    private javax.swing.JButton print;
    private javax.swing.JTable tabel;
    private javax.swing.JRadioButton teh;
    private javax.swing.JRadioButton teler;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextArea total;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[]={"Makanan","Jumlah Makanan","Minuman","Jumlah Minuman"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_resto";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next())
           {
               String makan = rs.getString(1);
                String jml_mkn= rs.getString(2);
                String minum = rs.getString(3);
                String jml_minum = rs.getString(4);
//                String total = rs.getString(5);
                String data[] = {makan,jml_mkn,minum,jml_minum};
                dtm.addRow(data);
           }
       } catch(SQLException ex)
       {
           //Logger.getLogger(FormBiodata.class.getName()).Log(Level.SEVERE, null, ex);
       }
       tabel.setModel(dtm);
    }
}
